// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package checklist

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenEOF-0]
	_ = x[tokenHypen-1]
	_ = x[tokenText-2]
	_ = x[tokenCommand-3]
	_ = x[tokenError-4]
}

const _tokenType_name = "tokenEOFtokenHypentokenTexttokenCommandtokenError"

var _tokenType_index = [...]uint8{0, 8, 18, 27, 39, 49}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
